# Generated by Django 4.0.6 on 2022-07-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoderhouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('lanzamiento', models.DateField()),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Familia',
        ),
    ]
